wandb:
  entity: "poludmik"
  project: "codellama_LoRA"
hyperparameters:
  seed: 228
  split_ratio: 0.01 # 5% of the data is used for validation
  output_dir: "finetuning/lora/cp/codellama_python_new_2/"
  per_device_train_batch_size: 1
  per_device_eval_batch_size: 1
  gradient_accumulation_steps: 1
  eval_accumulation_steps: 1
  optim: "paged_adamw_32bit"
  save_steps: 50
  logging_steps: 1
  group_by_length: True
  ddp_find_unused_parameters: False
  run_name: "Cluster_LoRA_CL_Python"
  learning_rate: 0.001
  max_grad_norm: 0.3
  max_steps: 200
  warmup_ratio: 0.01
  evaluation_strategy: "steps"
  lr_scheduler_type: "constant"
  callback_nth: 1
  trainer:
    max_seq_length: 1520
  lora_config:
    r: 32
    alpha: 64
    dropout: 0.1
    target_modules: ["q_proj", "k_proj", "v_proj", "o_proj"] # , "k_proj", "v_proj", "o_proj"
    bias: "none"
    task_type: "CAUSAL_LM"
