wandb:
  entity: "poludmik"
  project: "codellama_LoRA"
hyperparameters:
  seed: 228
  split_ratio: 0.1 # 10% of the data is used for validation
  output_dir: "finetuning/lora/cp/"
  per_device_train_batch_size: 4
  per_device_eval_batch_size: 4
  gradient_accumulation_steps: 4
  eval_accumulation_steps: 4
  optim: "paged_adamw_32bit"
  save_steps: 10
  logging_steps: 1
  group_by_length: True
  ddp_find_unused_parameters: False
  run_name: "lora_finetuning_python"
  learning_rate: 5e-4
  max_grad_norm: 0.3
  max_steps: 10
  warmup_ratio: 0.1
  evaluation_strategy: "steps"
  lr_scheduler_type: "constant"
  callback_nth: 30
  trainer:
    max_seq_length: 250
  lora_config:
    r: 8
    alpha: 16
    dropout: 0.1
    target_modules: [ "q_proj", "k_proj", "v_proj", "o_proj" ]
    bias: "none"
    task_type: "CAUSAL_LM"
