[tool.poetry]
name = "agenttobenamed"
version = "0.1.0"
description = ""
authors = ["poludmik <michael.poludin@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pandas = "^2.1.3"
openai = "^1.3.2"
langchain = "^0.0.336"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
