params:
  output_dir: evaluation/results_8bit/
  tables_dataset_dir: dataset/dataset_tables/
  excel: dataset/dataset_clean.xlsx
  max_debug_times: 0
  reasoning_llm: gpt-3.5-turbo-1106
  coding_llm: codellama/CodeLlama-7b-Instruct-hf
  head_number: 2
  output_filename: filled_dataset.xlsx
